In [1]:
import numpy as np

In [ ]:
## ndarray 생성과 배열 조작
# 1.
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# 2.
arr = np.ones((5, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 3.
arr = np.linspace(0, 1, 20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
# 4.
arr = np.random.randn(12).reshape(3, 4).copy()
print(arr)

[[ 0.69608442  1.31580135  1.09720629 -2.03269052]
 [-0.68674156 -0.21589751  1.26435729 -0.65675002]
 [ 0.11301749 -0.68284368 -0.47013389  0.78227757]]


In [ ]:
# 5.
arr = np.arange(1, 10).reshape(3, 3).copy()
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 6.
arr = np.zeros((5, 5))
arr[1:4,1:4] = 1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# 7.
arr = np.arange(1, 10).reshape(3, 3).copy()
print(arr * arr)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# 8.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


In [ ]:
# 9.
arr = np.zeros((3, 3))
print(f'배열의 데이터 타입: {arr.dtype}')
print(f'배열의 차원 수: {arr.ndim}')
print(f'배열의 모양: {arr.shape}')

배열의 데이터 타입: float64
배열의 차원 수: 2
배열의 모양: (3, 3)


In [ ]:
# 10.
arr = np.random.randint(0, 100, (10,))
print(arr)

[76  9 43 56 69  1 26  2 82 20]


In [ ]:
## ndarray indexing과 slicing
# 1.
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


In [ ]:
# 2.
arr = np.arange(1, 10).reshape(3, 3).copy()
print(arr[1,1])

5


In [ ]:
# 3.
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [ ]:
# 4.
arr = np.arange(1, 13).reshape(3, 4).copy()
print(arr[0:2,1:3])

[[2 3]
 [6 7]]


In [ ]:
# 5.
arr = np.arange(1, 19).reshape(3, 2, 3).copy()
print(arr[1,0,:])

[7 8 9]


In [ ]:
# 6.
arr = np.arange(1, 17).reshape(4, 4).copy()
print(np.diag(arr))

[ 1  6 11 16]


In [ ]:
# 7.
arr = np.arange(1, 11)
print(arr[(arr % 2) == 0])

[ 2  4  6  8 10]


In [ ]:
# 8.
arr = np.arange(1, 17).reshape(4, 4).copy()
print(arr[arr >= 5])

[ 5  6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
# 9.
arr = np.arange(10)
arr[3:6] = -1
print(arr)

[ 0  1  2 -1 -1 -1  6  7  8  9]


In [ ]:
# 10.
arr = np.arange(1, 17).reshape(4, 4).copy()
temp = np.zeros((4, 4))
temp[1:3,1:3] = arr[1:3,1:3]
print(temp)

[[ 0.  0.  0.  0.]
 [ 0.  6.  7.  0.]
 [ 0. 10. 11.  0.]
 [ 0.  0.  0.  0.]]


In [ ]:
# 11.
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])
arr = arr[arr > 20]
arr = arr[arr < 50]
print(arr)

[25 30 35 40 45]


In [ ]:
# 12.
arr_2d = np.arange(1, 17).reshape(4, 4).copy()
print(arr_2d[np.ix_([0, 2], [1, 3])])

[[ 2  4]
 [10 12]]


In [ ]:
# 13.
arr = np.array([[12, 15, 22, 29],
                [5, 18, 21, 30],
                [14, 17, 13, 20]])
arr[arr > 20] = 0
print(arr)

[[12 15  0  0]
 [ 5 18  0  0]
 [14 17 13 20]]


In [5]:
# 14.
arr = np.array([[10, 15, 20, 25],
                [30, 35, 40, 45],
                [50, 55, 60, 65],
                [70, 75, 80, 85]])
print(np.where((arr > 40) & ((arr%2) == 0)))
arr1 = np.where((arr > 40) & ((arr%2) == 0), 0, arr)
print(arr1)

(array([2, 2, 3, 3]), array([0, 2, 0, 2]))
[[10 15 20 25]
 [30 35 40 45]
 [ 0 55  0 65]
 [ 0 75  0 85]]
