In [ ]:

import numpy as np

# 난수의 재현을 구현하기 위해서 사용.
np.random.seed(1)

# random으로 ndarray를 생성해보아요!
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print()

# reshape()은 view를 만들어내요!
# resize()는 reshape()과 다르게 동작해요!
# resize()는 numpy가 제공하는 함수이면서 ndarray의 method(자기 자신이 바뀜)에요!
arr1 = np.resize(arr, (2, 6))
print(arr1)
print()

arr[0][0] = 100
print(arr)
print(arr1)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]

[[5 8 9 5 0 0]
 [1 7 6 9 2 4]]

[[100   8   9   5]
 [  0   0   1   7]
 [  6   9   2   4]]
[[5 8 9 5 0 0]
 [1 7 6 9 2 4]]


In [ ]:

np.random.seed(1)

# random으로 ndarray를 생성해보아요!
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print()

arr1 = arr.resize(2, 6)
print(arr1)
print()

arr.resize(2, 6)
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]

None

[[5 8 9 5 0 0]
 [1 7 6 9 2 4]]


In [ ]:
np.random.seed(1)

# random으로 ndarray를 생성해보아요!
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print()

arr.resize(2, 7) # 가능. reshape()은 불가능!
print(arr)
print()

arr.resize(2, 2)
print(arr)

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]

[[5 8 9 5 0 0 1]
 [7 6 9 2 4 0 0]]

[[5 8]
 [9 5]]


In [ ]:

# indexing과 slicing에 대해서 알아보아요!
import numpy as np

# ndarray를 하나 생성해요!
arr = np.arange(10, 20, 1) # 1차원 ndarray를 생성
print(arr)
print()

print(arr[0])
arr[0] = 100
print(arr)
print()

# python 배울 때 slicing에 대해서 배웠어요!
# slicing은 원본의 형태(list 형태)를 유지해요!
# python의 list는 slicing을 할 때 새로운 list가 생성
my_list1 = [1, 2, 3, 4, 5]
my_list2 = my_list1[0:2]
print(my_list1)
print(my_list2)
print()

# numpy의 ndarray를 slicing하면 view가 만들어져요!
arr = np.arange(0, 5, 1)
arr1 = arr[0:2]
print(arr)
print(arr1)
print()

arr[0] = 100
print(arr)
print(arr1)

[10 11 12 13 14 15 16 17 18 19]

10
[100  11  12  13  14  15  16  17  18  19]

[1, 2, 3, 4, 5]
[1, 2]

[0 1 2 3 4]
[0 1]

[100   1   2   3   4]
[100   1]


In [ ]:

# 2차원 ndarray의 indexing과 slicing
# 1~16까지 정수를 이용해서 4행 4열의 2차원 ndarray를 생성하세요!
arr = np.arange(1, 17).reshape(4, 4)
print(arr)
print()

print(arr[1,1])
print(arr[2,:])
print(arr[1:3,:])
print(arr[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

6
[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7]
 [10 11]]


In [ ]:

# Boolean indexing과 Fancy indexing

# Boolean indexing은 배열의 각 요소의 선택여부를
# True, False로 구성된 Boolean Mask를 이용하여 indexing하는 방식
# Boolean Mask에서 True로 구성된 요소만 추출하는 indexing 방법
np.random.seed(1)
arr = np.random.randint(0, 10, (10,))
print(arr)
print()

# Boolean indexing을 하려면 Boolean Mask가 필요!
# Boolean Mask는 indexing 하려는 ndarray와 shape이 같아요!
# 단, 그 안의 값은 True, False로 구성되어야 해요!
mask1 = np.array([True, False, True, False, True, False, True, False, True, False])
print(mask1)
print(arr[mask1])
print()

mask2 = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0]) # 안됨.
print(mask2)
print(arr[mask2])
print()

# numpy 연산은 list연산과 달라요!
# 실제 수치연산을 수행하고 같은 위치에 있는 것끼리 연산을 수행해요.
# 만약 shape이 다르면 broadcasting을 이용해서 shape을 맞춰서 연산을 수행해요.
# 만약 shape을 맞출 수 없으면 오류에요!
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(list_1 + list_2)
print(arr1 + arr2)
print(arr1 + 1) # Broad Casting
print()

# 주어진 ndarray에서 짝수만 추출하세요!
mask3 = (arr % 2 == 0)
print(arr)
print(mask3)
print(arr[mask3])
print(arr[(arr % 2) == 0])

[5 8 9 5 0 0 1 7 6 9]

[ True False  True False  True False  True False  True False]
[5 9 0 1 6]

[1 1 1 1 1 0 0 0 0 0]
[8 8 8 8 8 5 5 5 5 5]

[1, 2, 3, 4, 5, 6]
[5 7 9]
[2 3 4]

[5 8 9 5 0 0 1 7 6 9]
[False  True False False  True  True False False  True False]
[8 0 0 6]
[8 0 0 6]


In [ ]:

# Fancy indexing은 ndarray에 index 배열을 전달해서 배열 요소를 참조하는 방식
arr = np.arange(12).reshape(3, 4).copy()
print(arr)
print(arr[1,2])
print(arr[1,2:3])
print(arr[1:2,2])
print(arr[1:2,2:3])
print(arr[:,2])
print()

# Fancy indexing
print(arr[[0,2],2])
print()

# Fancy indexing의 추가사항 하나만 알아두면 되요!
print(arr[[0,2],[0,2]]) # X
print(arr[np.ix_([0,2],[0,2])]) # O

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[6]
[6]
[[6]]
[ 2  6 10]

[ 2 10]

[ 0 10]
[[ 0  2]
 [ 8 10]]


In [ ]:

# ndarray의 생성
# ndarray의 함수 및 속성
# ndarray의 indexing과 slicing
# ndarray의 연산

# 기본적으로 ndarray의 사칙연산은 같은 shape의 ndarray까리 이루어져요!
# 위치가 같은 놈끼리 연산을 수행해야 하기 때문에

# 만약 shape이 다르다면 바로 오류를 내지는 않아요!
# 최대한 shape을 맞추려고 노력해요! => broadcasting이 발생

arr = np.arange(1, 13).reshape(3, 4).copy()
print(arr)
print()
print(arr * 3)
print()
print(arr + np.array([1, 2, 3, 4]))

# 결국 대부분의 연산은 같은 shape의 ndarray끼리 이루어져요!

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


In [1]:

import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.arange(10, 16, 1).reshape(3, 2).copy()

print(arr1)
print(arr2)
print(np.matmul(arr1, arr2))

[[1 2 3]
 [4 5 6]]
[[10 11]
 [12 13]
 [14 15]]
[[ 76  82]
 [184 199]]


In [4]:
# 일반적인 사칙연산 외에 함수형태로 제공되는 연산이 있어요!
# 2차원 ndarray 하나 생성해서 함수들을 알아보아요!
arr = np.arange(1, 7).reshape(2, 3).copy()
print(arr)
print()

# 합을 구해보아요!
# 이런 연산은 우리가 일반적으로 프로그램에서 하듯이
# 로직을 이용해서 구현하면 (for 돌리고 변수선언하고...)
# 느리다! => 이런 작업을 빠르게 수행할 필요가 있어요!
print(np.sum(arr))
print(arr.sum())
print(np.cumsum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr)) # 최대값의 1차원적인 위치값(index)
print(np.argmin(arr))
print(np.std(arr))
print(np.sqrt(arr))
print(np.exp(arr))        # 자연상수의 제곱값 (자연상수 e = 2.7182...)
print(np.log10(arr))      # 상용 log의 값
print(np.log(arr))        # 자연 log의 값 (자연상수 e = 2.7182...)

[[1 2 3]
 [4 5 6]]

21
21
[ 1  3  6 10 15 21]
3.5
6
1
5
0
1.707825127659933
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [ ]:
# Numpy의 모든 집계함수는 axis를 기준으로 동작해요!
# 만약 이 axis(축)를 지정하지 않으면
# axis는 None으로 간주되고 모든 대상 영역이 전체 ndarray로 설정되요!
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())
print(arr.sum(axis=0)) # axis는 숫자값이에요! 즉, 숫자로 축을 지정
                        # axis의 값이 0이면 열(가장 고차원)을 의미(1차원(열)인 경우)
                        # 열 방향으로 더해요!
# print(arr.sum(axis=1)) 이건 오류

15
15


In [5]:
arr = np.array([[1, 4, 8],
                [2, 5, 9],
                [7, 3, 6]])
print(arr)
print()
print(arr.sum()) # axis=None으로 설정
print(arr.sum(axis=0)) # 행(가장 고차원)을 의미 (2차원(행, 열)인 경우)
print(arr.sum(axis=1)) # 열(행 다음)
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))
print()

np.random.seed(1)
arr = np.random.randint(0, 5, (3, 2, 3))
print(arr)
print()

print(arr.sum())
print(arr.sum(axis=0)) # 면(가장 고차원)을 의미 (3차원(면, 행, 열)인 경우)
print(arr.sum(axis=1)) # 행
print(arr.sum(axis=2)) # 열

[[1 4 8]
 [2 5 9]
 [7 3 6]]

45
[10 12 23]
[13 16 16]
[2 1 1]
[2 2 0]

[[[3 4 0]
  [1 3 0]]

 [[0 1 4]
  [4 1 2]]

 [[4 2 4]
  [3 4 2]]]

42
[[7 7 8]
 [8 8 4]]
[[4 7 0]
 [4 2 6]
 [7 6 6]]
[[ 7  4]
 [ 5  7]
 [10  9]]
