In [ ]:
# Attention 연산의 Simple 버전
# 입력 문장
# -> Query, Key, Value 데이터를 생성
# -> Query와 Key의 유사도를 계산(내적) -> Attention Score
# -> Attention Score를 이용해서 Value의 가중합 -> Attention Output

In [ ]:
import numpy as np

# 입력 데이터는 '나는 너를 사랑해'
# 입력 데이터는 => ['나는', '너를', '사랑해']
token = ['나는', '너를', '사랑해']
# '나는' => [1.0, 0.0, 1.0] (Embedding)
# '너를' => [1.0, 1.0, 1.0] (Embedding)
# '사랑해' => [1.0, 1.0, 0.0] (Embedding)

# 원래는 값을 변환시켜서 사용해야 해요!
# 계산이 힘들어서 같은 값을 사용
key_vector = np.array([[1.0, 0.0, 1.0],  # '나는'
                       [1.0, 1.0, 1.0],  # '너를'
                       [1.0, 1.0, 0.0]]) # '사랑해'

value_vector = np.array([[10.0, 0.0, 0.0],  # '나는'
                         [0.0, 10.0, 0.0],  # '너를'
                         [0.0, 0.0, 10.0]]) # '사랑해'

query = key_vector[2] # [1.0, 1.0, 0.0] '사랑해'

# 1. 유사도 계산(내적을 이용해서 계산)
score = np.dot(key_vector, query)
print(score) # [1. 2. 2.]

# 2. 숫자의 안정화를 시키기 위해서 embedding의 차원의 root값을
#    이용해서 값을 나눠야 해요!
#    원래는 np.sqrt(3)을 구해서 각각의 값을 나눠줘야 해요!
#    지금은 생략!

# 3. softmax를 이용해서 확률값으로 변경
#    확률값으로 변경하려면 사실 쉬운 방법이 있어요!
#    모두 더한 후 그 값으로 각각의 값을 나눠주면 되요!
#    [0.2 0.4 0.4]
#    값이 큰 것에 더 가중치를 줘서 확률값으로 변경
def softmax(x):
    exp_x = np.exp(x - np.max(x)) # 지수 함수라서 값이 커지면 급격하게 결과값이 커져요!
    return exp_x / exp_x.sum()

attention_weighted = softmax(score)
print(attention_weighted) # [0.1553624 0.4223188 0.4223188] (3,)
# 결국 가중치를 구했어요!

print(attention_weighted[:, np.newaxis])
# [[0.1553624]
#  [0.4223188]
#  [0.4223188]] (3,1)

print(attention_weighted[:, np.newaxis] * value_vector)
# [[1.55362403 0.         0.        ]
#  [0.         4.22318798 0.        ]
#  [0.         0.         4.22318798]]

# 이를 이용해서 Attention Output을 구할 수 있어요!
print(np.sum(attention_weighted[:, np.newaxis] * value_vector,
             axis=0))
# [1.55362403 4.22318798 4.22318798]
# 이 값은 '사랑해'라는 Query의 Attention Output

[1. 2. 2.]
[0.1553624 0.4223188 0.4223188]
[[0.1553624]
 [0.4223188]
 [0.4223188]]
[[1.55362403 0.         0.        ]
 [0.         4.22318798 0.        ]
 [0.         0.         4.22318798]]
[1.55362403 4.22318798 4.22318798]
